#!/usr/bin/env bash
#
# Write .vscode/ros.env — the ROS environment, in the one format VSCode reads.
#
# VSCode's Python extension does not run tests through a shell: it spawns the
# selected interpreter directly with its own adapter script, so `source
# install/setup.bash` never happens. What the Testing panel sees instead is the
# environment of whatever launched VSCode — a desktop session that read no
# ~/.profile — where `import launch` fails, or worse, ament_index_python finds a
# *different* workspace's install/ and answers confidently. The one hook the
# extension offers is `python.envFile`, a flat KEY=VALUE file. This produces it.
#
# It is a *generated* file and therefore a staleness trap, so two things guard
# it: .vscode/tasks.json regenerates it on folder open, and the failure mode is
# loud — an AMENT_PREFIX_PATH missing a package fails the launch-file tests with
# PackageNotFoundError naming every path it searched, rather than passing over
# it. The file is git-ignored: it holds absolute paths and this machine's distro.
#
# Two sources, and the second is the one that is easy to leave out. The
# essentials below are written unconditionally, because a shell that had already
# sourced the overlay would show *no change* across the sourcing and produce a
# file missing every path VSCode lacks — a run of this script that looks like it
# worked. The diff on top of that catches whatever a future ROS setup script
# learns to set, which a hand-written list never would.

set -euo pipefail

WS=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
OUT="$WS/.vscode/ros.env"

# Read with -d '' so a value containing a newline stays one entry rather than
# becoming two malformed ones.
declare -A BEFORE=()
while IFS= read -r -d '' kv; do
    BEFORE["${kv%%=*}"]="${kv#*=}"
done < <(env -0)

set +u
# shellcheck source=/dev/null
. "$WS/tools/lib/ros-env.sh" --overlay
set -u

declare -A AFTER=()
while IFS= read -r -d '' kv; do
    AFTER["${kv%%=*}"]="${kv#*=}"
done < <(env -0)

# Written whether or not the sourcing changed them. The search paths are what
# make the workspace visible at all; RMW_IMPLEMENTATION and ROS_DOMAIN_ID come
# from ~/.profile rather than from setup.bash, and every test binary that links
# rcl checks the first of them at startup and exits 1 when it cannot be loaded.
ESSENTIAL=(PATH PYTHONPATH LD_LIBRARY_PATH PKG_CONFIG_PATH
           AMENT_PREFIX_PATH CMAKE_PREFIX_PATH COLCON_PREFIX_PATH
           ROS_DISTRO ROS_VERSION ROS_PYTHON_VERSION ROS_DOMAIN_ID
           RMW_IMPLEMENTATION CYCLONEDDS_URI ROS_AUTOMATIC_DISCOVERY_RANGE
           ROS_LOCALHOST_ONLY)

# Volatile per-shell bookkeeping. Handing these to VSCode would be wrong at best
# (PWD) and confusing at worst (_ is whatever ran last).
SKIP='^(_|PWD|OLDPWD|SHLVL|BASHPID|BASH_.*|RANDOM|SECONDS|LINENO|WS|OUT|kv|name)$'

declare -A EMIT=()
for name in "${ESSENTIAL[@]}"; do
    [[ -v AFTER[$name] ]] && EMIT["$name"]=1
done
for name in "${!AFTER[@]}"; do
    [[ $name =~ $SKIP ]] && continue
    [[ ${BEFORE[$name]-$'\x01'} == "${AFTER[$name]}" ]] && continue
    EMIT["$name"]=1
done

mkdir -p "$WS/.vscode"
{
    echo "# GENERATED by tools/lib/vscode-env.sh on $(date -Is) — do not edit, do not commit."
    echo "# Read by .vscode/settings.json as python.envFile. Regenerate after adding a"
    echo "# package, after a fresh clone, or after changing distro:"
    echo "#     bash tools/lib/vscode-env.sh"
    echo "# .vscode/tasks.json also runs it when the folder opens."
    echo
    for name in $(printf '%s\n' "${!EMIT[@]}" | sort); do
        value=${AFTER[$name]}
        [[ -n $value ]] || continue
        if [[ $value == *$'\n'* ]]; then
            echo "vscode-env: skipping $name — a .env file cannot hold a newline" >&2
            continue
        fi
        printf '%s=%s\n' "$name" "$value"
    done
} > "$OUT"

# The assertion, rather than a count of lines written: the whole point of the
# file is that this workspace's install/ is on the search path, and a file that
# is merely large can still be missing it.
if ! grep -q "^AMENT_PREFIX_PATH=.*$WS/install" "$OUT"; then
    echo "vscode-env: $WS/install is not on AMENT_PREFIX_PATH — build first" >&2
    exit 1
fi

echo "vscode-env: wrote $(grep -c '^[A-Z]' "$OUT") variables to ${OUT#"$WS"/}"
